

set(JUGICINEHL_SOURCES
logic/jpLogicState.h
logic/jpLogicAction.h
logic/jpSceneLogicState.h
logic/jpLogicStateCfg.h
logic/jpConditions.h
logic/jpCommands.h
logic/jpFunction.h
logic/jpLogicCommon.h
logic/jpTransition.h
logic/jpTransitionOperations.h
items/jpItemsCommon.h
items/jpItemSlotData.h
components/jpComponentsCommon.h
components/jpUserSelector.h
components/jpInputCustomizer.h
components/jpNewUserPanel.h
components/jpLanguageSelector.h
components/jpConfirmPanel.h
components/jpMessagePanel.h
gfxObjects/jpGfxObjectsCommon.h
gfxObjects/jpAnimationObjects.h
gfxObjects/jpCompound.h
gfxObjects/jpMoving.h
gui/jpGuiCommon.h
gui/jpGuiSystem.h
gui/jpGuiUtilities.h
gui/widgets/jpGuiBar.h
gui/widgets/jpGuiButton.h
gui/widgets/jpGuiSlider.h
gui/widgets/jpGuiTextField.h
gui/widgets/jpGuiTextInput.h
gui/widgets/jpGuiTable.h
gui/widgets/jpGuiSlot.h
gui/widgets/jpGuiTableNew.h
entitySystem/jpEntity.h
entitySystem/jpEntitySystem.h
entitySystem/jpEntityPhase.h
entitySystem/jpEntityManager.h
entitySystem/jpEntityCommon.h
entitySystem/jpEntityGlobal.h
entitySystem/jpEntityGroups.h
entitySystem/jpEntityUtilities.h
entitySystem/jpSourceEntity.h
entitySystem/jpEntityCharacter.h
entitySystem/jpB2Callbacks.h
entitySystem/jpB2Body.h
entitySystem/jpB2Fixture.h
entitySystem/jpB2World.h
entitySystem/jpB2DebugDraw.h
entitySystem/jpB2Utilities.h
entitySystem/jpEntityLogicState.h
entitySystem/movements/jpMovementBase.h
entitySystem/movements/jpMovementCommon.h
entitySystem/movements/jpSpeedGenerators.h
entitySystem/movements/jpGroundMovement.h
entitySystem/movements/jpJumpMovement.h
entitySystem/movements/jpPathMovement.h
entitySystem/movements/jpPathPtPMovement.h
entitySystem/movements/jpAnimatedBehavior.h
entitySystem/movements/jpAngularVelocity.h
entitySystem/movements/jpCustomState.h
entitySystem/task/jpTaskBase.h
entitySystem/task/jpTaskCommon.h
entitySystem/task/jpTransporter.h
character/jpCharacterAction.h
data/jpDataUtilities.h
data/jpData.h
data/jpItem.h
systems/jpSettings.h
systems/jpUser.h
systems/jpInput.h
systems/jpSystemVarious.h
jpGlobal.h
jpObjectFactory.h
jpVariables.h
jpGameObjectsLoader_xml.h
jpUtilities.h
jpQueries.h
jpObjectParser.h
jpAttribute.h
jpPlayedApp.h
jpPlayedScene.h

logic/jpLogicState.cpp
logic/jpLogicAction.cpp
logic/jpSceneLogicState.cpp
logic/jpLogicStateCfg.cpp
logic/jpConditions.cpp
logic/jpCommands.cpp
logic/jpFunction.cpp
logic/jpLogicCommon.cpp
logic/jpTransition.cpp
logic/jpTransitionOperations.cpp
items/jpItemsCommon.cpp
items/jpItemSlotData.cpp
components/jpComponentsCommon.cpp
components/jpUserSelector.cpp
components/jpInputCustomizer.cpp
components/jpNewUserPanel.cpp
components/jpLanguageSelector.cpp
components/jpConfirmPanel.cpp
components/jpMessagePanel.cpp
gfxObjects/jpGfxObjectsCommon.cpp
gfxObjects/jpAnimationObjects.cpp
gfxObjects/jpCompound.cpp
gfxObjects/jpMoving.cpp
gui/jpGuiCommon.cpp
gui/jpGuiSystem.cpp
gui/jpGuiUtilities.cpp
gui/widgets/jpGuiBar.cpp
gui/widgets/jpGuiButton.cpp
gui/widgets/jpGuiSlider.cpp
gui/widgets/jpGuiTextField.cpp
gui/widgets/jpGuiTextInput.cpp
gui/widgets/jpGuiTable.cpp
gui/widgets/jpGuiSlot.cpp
gui/widgets/jpGuiTableNew.cpp
entitySystem/jpEntity.cpp
entitySystem/jpEntitySystem.cpp
entitySystem/jpEntityPhase.cpp
entitySystem/jpEntityManager.cpp
entitySystem/jpEntityCommon.cpp
entitySystem/jpEntityGlobal.cpp
entitySystem/jpEntityGroups.cpp
entitySystem/jpEntityUtilities.cpp
entitySystem/jpSourceEntity.cpp
entitySystem/jpEntityCharacter.cpp
entitySystem/jpB2Callbacks.cpp
entitySystem/jpB2Body.cpp
entitySystem/jpB2Fixture.cpp
entitySystem/jpB2World.cpp
entitySystem/jpB2DebugDraw.cpp
entitySystem/jpB2Utilities.cpp
entitySystem/jpEntityLogicState.cpp
entitySystem/movements/jpMovementBase.cpp
entitySystem/movements/jpMovementCommon.cpp
entitySystem/movements/jpSpeedGenerators.cpp
entitySystem/movements/jpGroundMovement.cpp
entitySystem/movements/jpJumpMovement.cpp
entitySystem/movements/jpPathMovement.cpp
entitySystem/movements/jpPathPtPMovement.cpp
entitySystem/movements/jpAnimatedBehavior.cpp
entitySystem/movements/jpAngularVelocity.cpp
entitySystem/movements/jpCustomState.cpp
entitySystem/task/jpTaskBase.cpp
entitySystem/task/jpTaskCommon.cpp
entitySystem/task/jpTransporter.cpp
character/jpCharacterAction.cpp
data/jpDataUtilities.cpp
data/jpData.cpp
data/jpItem.cpp
systems/jpSettings.cpp
systems/jpUser.cpp
systems/jpInput.cpp
systems/jpSystemVarious.cpp
jpGlobal.cpp
jpObjectFactory.cpp
jpVariables.cpp
jpGameObjectsLoader_xml.cpp
jpUtilities.cpp
jpQueries.cpp
jpObjectParser.cpp
jpAttribute.cpp
jpPlayedScene.cpp
jpPlayedApp.cpp

)

