

set(JUGICINEHL_SOURCES
actions/jpActionsCommon.h
actions/jpCommands_Logic.h
actions/jpTransition.h
actions/jpTransitionOperations.h
actions/jpCommands_Gui.h
actions/jpTriggers_Logic.h
actions/jpTriggers_Gui.h
actions/jpTriggers_Input.h
actions/jpConditions.h
widgets/jpItemsTable.h
items/jpItemsCommon.h
items/jpItemSlotData.h
components/jpComponentsCommon.h
components/jpUserSelector.h
components/jpInputCustomizer.h
components/jpNewUserPanel.h
components/jpLanguageSelector.h
components/jpConfirmPanel.h
components/jpMessagePanel.h
gfxObjects/jpGfxObjectsCommon.h
gfxObjects/jpAnimationObjects.h
entitySystem/jpEntity.h
entitySystem/jpEntitySystem.h
entitySystem/jpEntityCommon.h
entitySystem/jpEntityGlobal.h
entitySystem/jpEntityGroups.h
entitySystem/jpEntityUtilities.h
entitySystem/jpSourceEntity.h
entitySystem/jpB2Callbacks.h
entitySystem/jpB2Body.h
entitySystem/jpB2Fixture.h
entitySystem/jpB2World.h
entitySystem/jpB2DebugDraw.h
entitySystem/jpB2Utilities.h
entitySystem/scripting/jpBehavior.h
entitySystem/scripting/jpBehCfg.h
entitySystem/scripting/jpBehConditions.h
entitySystem/scripting/jpBehCommands.h
entitySystem/movements/jpMovementBase.h
entitySystem/movements/jpMovementCommon.h
entitySystem/movements/jpSpeedGenerators.h
entitySystem/movements/jpGroundMovement.h
entitySystem/movements/jpJumpMovement.h
entitySystem/movements/jpPathMovement.h
entitySystem/movements/jpPathPtPMovement.h
entitySystem/movements/jpAnimatedBehavior.h
entitySystem/movements/jpAngularVelocity.h
entitySystem/task/jpTaskBase.h
entitySystem/task/jpTaskCommon.h
entitySystem/task/jpTransporter.h
systems/jpSettings.h
systems/jpUser.h
systems/jpInput.h
systems/jpSystemVarious.h
jpGlobal.h
jpObjectFactory.h
jpVariables.h
jpGameObjectsLoader_xml.h
jpUtilities.h
jpQueries.h
jpPlayedApp.h
jpPlayedScene.h

actions/jpActionsCommon.cpp
actions/jpCommands_Logic.cpp
actions/jpCommands_Gui.cpp
actions/jpTransition.cpp
actions/jpTransitionOperations.cpp
actions/jpTriggers_Logic.cpp
actions/jpTriggers_Gui.cpp
actions/jpTriggers_Input.cpp
actions/jpConditions.cpp
widgets/jpItemsTable.cpp
items/jpItemsCommon.cpp
items/jpItemSlotData.cpp
components/jpComponentsCommon.cpp
components/jpUserSelector.cpp
components/jpInputCustomizer.cpp
components/jpNewUserPanel.cpp
components/jpLanguageSelector.cpp
components/jpConfirmPanel.cpp
components/jpMessagePanel.cpp
gfxObjects/jpGfxObjectsCommon.cpp
gfxObjects/jpAnimationObjects.cpp
entitySystem/jpEntity.cpp
entitySystem/jpEntitySystem.cpp
entitySystem/jpEntityCommon.cpp
entitySystem/jpEntityGlobal.cpp
entitySystem/jpEntityGroups.cpp
entitySystem/jpEntityUtilities.cpp
entitySystem/jpSourceEntity.cpp
entitySystem/jpB2Callbacks.cpp
entitySystem/jpB2Body.cpp
entitySystem/jpB2Fixture.cpp
entitySystem/jpB2World.cpp
entitySystem/jpB2DebugDraw.cpp
entitySystem/jpB2Utilities.cpp
entitySystem/scripting/jpBehavior.cpp
entitySystem/scripting/jpBehCfg.cpp
entitySystem/scripting/jpBehConditions.cpp
entitySystem/scripting/jpBehCommands.cpp
entitySystem/movements/jpMovementBase.cpp
entitySystem/movements/jpMovementCommon.cpp
entitySystem/movements/jpSpeedGenerators.cpp
entitySystem/movements/jpGroundMovement.cpp
entitySystem/movements/jpJumpMovement.cpp
entitySystem/movements/jpPathMovement.cpp
entitySystem/movements/jpPathPtPMovement.cpp
entitySystem/movements/jpAnimatedBehavior.cpp
entitySystem/movements/jpAngularVelocity.cpp
entitySystem/task/jpTaskBase.cpp
entitySystem/task/jpTaskCommon.cpp
entitySystem/task/jpTransporter.cpp
systems/jpSettings.cpp
systems/jpUser.cpp
systems/jpInput.cpp
systems/jpSystemVarious.cpp
jpGlobal.cpp
jpObjectFactory.cpp
jpVariables.cpp
jpGameObjectsLoader_xml.cpp
jpUtilities.cpp
jpQueries.cpp
jpPlayedScene.cpp
jpPlayedApp.cpp

)

