

set(JUGIMAP_SOURCES
map/jmLayerElement.h
map/jmLayer.h
map/jmSpriteLayer.h
map/jmVectorLayer.h
map/jmMap.h
map/jmSprite.h
map/jmStandardSprite.h
map/jmTextSprite.h
map/jmCompositeSprite.h
map/jmSpriteModifiers.h
map/jmVectorShape.h
map/jmVectorShapeUtilities.h
map/jmVectorShapeDrawing.h
source/jmSourceContainers.h
source/jmSourceSprite.h
source/jmSourceFile.h
source/jmSourceItem.h
source/jmColor.h
source/jmFont.h
source/jmSystemSourceObjects.h
source/jmSourceObjectsLoader_xml.h
animation/jmAnimationCommon.h
animation/jmTimelineAnimation.h
animation/jmTimelineAnimationInstance.h
animation/jmFrameAnimation.h
gui/jmGuiCommon.h
gui/jmGuiBar.h
gui/jmGuiButton.h
gui/jmGuiSlider.h
gui/jmGuiTextField.h
gui/jmGuiTextInput.h
gui/jmGuiText.h
jmApp.h
jmScene.h
jmSceneLayout.h
jmCamera.h
jmCollision.h
jmCommon.h
jmCommonFunctions.h
jmSystem.h
jmGlobal.h
jmScene.h
jmUtilities.h
jmStreams.h
jmInput.h
jugimap.h
jmMapLoader_bin.h
jmParameter.h
jmSaveSignatures.h
jmTimer.h
jmTween.h
jmSignal.h
jmUsingDeclarations.h

map/jmLayerElement.cpp
map/jmLayer.cpp
map/jmSpriteLayer.cpp
map/jmVectorLayer.cpp
map/jmMap.cpp
map/jmSprite.cpp
map/jmStandardSprite.cpp
map/jmTextSprite.cpp
map/jmCompositeSprite.cpp
map/jmSpriteModifiers.cpp
map/jmVectorShape.cpp
map/jmVectorShapeUtilities.cpp
map/jmVectorShapeDrawing.cpp
source/jmSourceContainers.cpp
source/jmSourceSprite.cpp
source/jmSourceFile.cpp
source/jmColor.cpp
source/jmFont.cpp
source/jmSourceItem.cpp
source/jmSystemSourceObjects.cpp
source/jmSourceObjectsLoader_xml.cpp
animation/jmAnimationCommon.cpp
animation/jmTimelineAnimation.cpp
animation/jmTimelineAnimationInstance.cpp
animation/jmFrameAnimation.cpp
gui/jmGuiCommon.cpp
gui/jmGuiBar.cpp
gui/jmGuiButton.cpp
gui/jmGuiSlider.cpp
gui/jmGuiTextField.cpp
gui/jmGuiTextInput.cpp
gui/jmGuiText.cpp
jmApp.cpp
jmScene.cpp
jmSceneLayout.cpp
jmCamera.cpp
jmCollision.cpp
jmCommon.cpp
jmCommonFunctions.cpp
jmGlobal.cpp
jmSystem.cpp
jmUtilities.cpp
jmStreams.cpp
jmInput.cpp
jmMapLoader_bin.cpp
jmParameter.cpp
jmTimer.cpp
jmTween.cpp
jmSignal.cpp

)

